### ISSUE TITLE
Reload button moves when resizing Issues dialog

### ISSUE THREAD

**Issue by MALfunction84** [dail8859/TurtleHub#1]
The Reload button on the Issues dialog is positioned relative to the top-left corner instead of the bottom-left. This means if you make the dialog shorter, the Reload button is not visible, and if you make the dialog taller, it overlaps with the list of issues.

**Comment by dail8859** [comment]
Hi, thanks for the bug report. However this was just a few day project I did for fun a while ago and don't plan on updating it. You may try submitting this bug report over [here](https://github.com/machmet/TurtleHub) since it appears someone else has recently forked this repo and made a few updates. Glad to see that someone is using it at least :)

**Comment by MALfunction84** [comment]
Understood. Refiled over [here](https://github.com/machmet/TurtleHub/issues/2).
