### ISSUE TITLE
format for external issue numbers

### ISSUE THREAD

**Issue by Vankog** [dail8859/TurtleHub#4]
Hey,

I set up turtlehub to fetch from an upstream repo which I forked from. However, just inserting ```#1234``` in the logs is not sufficient for Github to parse the correct issue from this, because it is not in the current repo but an external one. For this we need the syntax ```another-user/other-repo#1234```

To work around this I tried using e.g. ```another-user/other-repo``` as keyword, but it parses to 
```another-user/other-repo #1234```
with a space.

This is, because you are inserting a space over here in line 81:
https://github.com/dail8859/TurtleHub/blob/73301d003fc9a01e3ad8e03f46b5b15f6bf5ff13/src/TurtleHub/Plugin.cs#L81

I have some ideas to do this: 
- Remove the forced space on this line. In which case the user should be responsible for the space.
- Or add a parameter, that enables the use of the ```another-user/other-repo#1234``` syntax. TurtleHub already has the required data for this, so it might be of limited effort and is backwards compatible.
- ...?

**Comment by dail8859** [comment]
Glad to see someone is using this :)

So if I understand you correctly you would like to see the commit be able to [close an issue in another repository](https://help.github.com/articles/closing-issues-using-keywords/#closing-an-issue-in-a-different-repository), so that instead of just inserting `Closes #1234` you could have it instead insert `Closes another-user/other-repo#1234`, correct?

**Comment by Vankog** [comment]
yep :-)

See commit message of this usecase:
Vankog/TurtleHub@685858df1cc7a743fe084c02feccbd72dfa2518a

However, as we usually don't have write permission on external repositories, the currently pre-provided keywords don't seem to fit that well. I suggest adding a blank keyword or "Issue" or something alike to the list.

**Comment by dail8859** [comment]
So I guess there are two different but kind of related things to address...

1. The keyword - The current list of keywords are the ones that Github recognizes that can close issues...which is the main focus of this plugin. However adding a blank and/or custom option seems reasonable for users that just want to reference individual issues/PRs instead of closing them. At least for now you can manually edit the string to use a custom keyword.

2. Referencing the issue - As you are aware it just defaults to `#1234`. There could be an option to reference the issue with the username and reponame.

This way you could a) select a custom keyword such as "See" and then b) set the option to reference the full repo path. That way if you select an issue it would then insert:

> See another-user/other-repo#1234

**Comment by Vankog** [comment]
exactly what I was grasping for ^^
