### ISSUE TITLE
fetch Pull Requests

### ISSUE THREAD

**Issue by Vankog** [dail8859/TurtleHub#5]
hey!

Could you please also fetch pull requests? 
I set up turtlehub to fetch from an upstream repo (see #4) where I open PRs in and I'd like to have them available for selection.

Would be really great! :-)

**Comment by dail8859** [comment]
I had filtered those out originally since in most cases it is just issues that need to be addressed, but since PRs can also get closed I don't see any reason they need filtered out. Probably a simple checkbox on the main dialog to show/hide PRs would be sufficient.

I'm not sure if I have my dev environment set up to build TurtleHub still (since I rarely use C#) but I'll look into it. I certainly welcome anyone that wants to submit a PR.

**Comment by Vankog** [comment]
For me the main focus is not on the keywords. They are secondary. I just like to cross-reference without necessarily automating the workflow of an issue or PR.

**Comment by dail8859** [comment]
@Vankog You are welcome to try out the latest fixes and let me know how they work for you. Below you can download one of the installers (you will have to rename the file and remove the `.txt` extension because Github doesn't allow uploading files just with `.msi`). If all is well I can release this as the official v0.3 version.


[TurtleHub-0.3.0-x64.msi.txt](https://github.com/dail8859/TurtleHub/files/1309190/TurtleHub-0.3.0-x64.msi.txt)
[TurtleHub-0.3.0-x86.msi.txt](https://github.com/dail8859/TurtleHub/files/1309189/TurtleHub-0.3.0-x86.msi.txt)

**Comment by Vankog** [comment]
x64 seems to work perfectly fine! :-)
Nice work!
