### ISSUE TITLE
Persistent "Show Pull Requests" setting

### ISSUE THREAD

**Issue by Vankog** [dail8859/TurtleHub#9]
Could you please make the "Show Pull Requests" selection persistent?
It is a little bit tedious if I have to enable it everytime again and again. ^^

Thank you! :-)

**Comment by dail8859** [comment]
The fix to this adds a new option to show PRs by default in the options dialog.

![capture](https://user-images.githubusercontent.com/3694843/30671755-9c5bf5f4-9e36-11e7-8705-80d1ceeac797.PNG)

I had originally tried to make so that whatever was last selected for "Show Pull Requests" would be persistent, however as far as I know TortoiseGit does not provide the ability to save parameters while showing the issue browser.

**Comment by Vankog** [comment]
What a pity. But this might be suitable as well. Thanks!

I'm not sure about the wording, though. From a new user's perspective this sounds as if *only* the Pull Requests would be visible by default when activating this (like a filter gets activated). But as you know it is the other way around: It *also* shows Pull Requests (the filter gets deactivated). 
What do you think about: *"Also Show Pull Requests by Default"*

**Comment by dail8859** [comment]
I might change it to something like "Include Pull Requests by Default".  I'll give it some thought and hopefully review your pull request sometime next week and get an official release out.

**Comment by Vankog** [comment]
Take your time.
